version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      MONGO_URL: "mongodb://mongo:27017/pocdb"
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  docs:
    build:
      context: ./docs
      dockerfile: Dockerfile
    ports:
      - "3001:3001"

volumes:
  mongo-data: