version: "3.9"
services:
  backend:
    build: ./back
    ports:
      - "5001:5000"
    environment:
      MONGO_URL: "mongodb://mongo:27017/pocdb"
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  frontend:
    build: ./front
    ports:
      - "3000:80"
    depends_on:
      - backend

  docs:
    build: ./docs
    ports:
      - "8000:8000"
    volumes:
      - ./docs:/docs
    working_dir: /docs
    command: ["mkdocs", "serve", "-a", "0.0.0.0:8000"]

volumes:
  mongo-data:
