graph LR

classDef GET fill:#4caf50,stroke:#333,stroke-width:1px,color:#fff,rx:10,ry:10;
classDef POST fill:#2196f3,stroke:#333,stroke-width:1px,color:#fff,rx:10,ry:10;
classDef PUT fill:#ff9800,stroke:#333,stroke-width:1px,color:#fff,rx:10,ry:10;
classDef DELETE fill:#f44346,stroke:#333,stroke-width:1px,color:#fff,rx:10,ry:10;
classDef LAYER fill:#b3e5fc,stroke:#333,stroke-width:1px,color:#333;


subgraph Endpoints
  GET_product_715(("GET product/"))
end

subgraph Logic
  Controller_controller.getProducts_0[/controller.getProducts/]
end

subgraph Data Layer
  database_product[/Database/]
end

  Client --> GET_product_715
  GET_product_715 --> Controller_controller.getProducts_0
  Controller_controller.getProducts_0 --> database_product

  class GET_product_715 GET;
  class Controller_controller.getProducts_0 LAYER;

