name: Generate Architecture Docs & Swagger

on:
  push:
    branches:
      - main 
      - dev 
  pull_request:
    branches:
      - main 

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' 

      - name: Install dependencies
        run: npm install 

      - name: Generate Swagger Docs
        run: node backend/scripts/generateSwagger.js
      
      - name: Run documentation script
        run: node backend/scripts/generateMermaid.js

      - name: Commit and Push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add docs/architecture.md docs/swagger.json
          git commit -m "chore(docs): Automatically generate docs [skip ci]" || echo "No changes to commit"
          git push